# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ice_cream.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fice_cream.proto\"1\n\x0fIceCreamRequest\x12\x0e\n\x06scoops\x18\x01 \x01(\x05\x12\x0e\n\x06\x66lavor\x18\x02 \x01(\t\"#\n\x10IceCreamResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2@\n\x08IceCream\x12\x34\n\rOrderIceCream\x12\x10.IceCreamRequest\x1a\x11.IceCreamResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ice_cream_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ICECREAMREQUEST']._serialized_start=19
  _globals['_ICECREAMREQUEST']._serialized_end=68
  _globals['_ICECREAMRESPONSE']._serialized_start=70
  _globals['_ICECREAMRESPONSE']._serialized_end=105
  _globals['_ICECREAM']._serialized_start=107
  _globals['_ICECREAM']._serialized_end=171
# @@protoc_insertion_point(module_scope)
